"""Ajout statut à Don

Revision ID: 1bc4bd586ad3
Revises: f4e0241fbfd8
Create Date: 2025-05-02 10:29:19.594546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc4bd586ad3'
down_revision = 'f4e0241fbfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
