"""Augmenter la taille du champ description

Revision ID: 265e4c2ef8ae
Revises: 1bc4bd586ad3
Create Date: 2025-05-02 15:28:31.245794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265e4c2ef8ae'
down_revision = '1bc4bd586ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=600),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
