"""ajout  cin date_naissance, adresse, profession

Revision ID: 3ebba2c2a604
Revises: fb031f120d88
Create Date: 2025-07-04 15:46:13.432210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebba2c2a604'
down_revision = 'fb031f120d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rne', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['rne'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cin', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('cin_recto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cin_verso', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('date_naissance', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('adresse', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['cin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('profession')
        batch_op.drop_column('adresse')
        batch_op.drop_column('date_naissance')
        batch_op.drop_column('cin_verso')
        batch_op.drop_column('cin_recto')
        batch_op.drop_column('cin')

    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rne')

    # ### end Alembic commands ###
