"""Ajout du champ sentiment aux commentaires

Revision ID: 3fa055d966b5
Revises: 9208ddeddad2
Create Date: 2025-05-07 12:23:11.561301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa055d966b5'
down_revision = '9208ddeddad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
