"""Ajout des champs fiscaux et gouvernorat à Association

Revision ID: 5539df33b593
Revises: 3ebba2c2a604
Create Date: 2025-07-11 16:22:51.498905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5539df33b593'
down_revision = '3ebba2c2a604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gouvernorats')
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule_fiscal', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cin_fiscale', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('releve_rib', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gouvernorat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gouvernorat', ['gouvernorat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gouvernorat_id')
        batch_op.drop_column('releve_rib')
        batch_op.drop_column('cin_fiscale')
        batch_op.drop_column('matricule_fiscal')

    op.create_table('gouvernorats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nomGouvernorat', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='gouvernorats_pkey'),
    sa.UniqueConstraint('nomGouvernorat', name='gouvernorats_nomGouvernorat_key')
    )
    # ### end Alembic commands ###
