"""Ajout des attributs id utilisateur et photo

Revision ID: 88754bb3878a
Revises: 2fde1db1cf1d
Create Date: 2025-04-07 16:37:57.416497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88754bb3878a'
down_revision = '2fde1db1cf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_don', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('id_utilisateur', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['id_utilisateur'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_utilisateur')
        batch_op.drop_column('photo_don')

    # ### end Alembic commands ###
