"""notifications

Revision ID: 8d665efc9d51
Revises: dc6a7ccb49f0
Create Date: 2025-09-24 15:19:19.762580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d665efc9d51'
down_revision = 'dc6a7ccb49f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_assoc_date', ['id_association', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id_association'), ['id_association'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id_don'), ['id_don'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id_publication'), ['id_publication'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id_user'), ['id_user'], unique=False)
        batch_op.create_unique_constraint('uq_notifications_don_once', ['id_association', 'id_don', 'contenu'])
        batch_op.create_unique_constraint('uq_notifications_pub_once', ['id_association', 'id_publication', 'contenu'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('uq_notifications_pub_once', type_='unique')
        batch_op.drop_constraint('uq_notifications_don_once', type_='unique')
        batch_op.drop_index(batch_op.f('ix_notifications_id_user'))
        batch_op.drop_index(batch_op.f('ix_notifications_id_publication'))
        batch_op.drop_index(batch_op.f('ix_notifications_id_don'))
        batch_op.drop_index(batch_op.f('ix_notifications_id_association'))
        batch_op.drop_index('ix_notifications_assoc_date')

    # ### end Alembic commands ###
