"""Ajout de id_publication dans Notification

Revision ID: 9208ddeddad2
Revises: acc0fe03b5e1
Create Date: 2025-05-06 16:25:59.596836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9208ddeddad2'
down_revision = 'acc0fe03b5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_publication', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'publications', ['id_publication'], ['id_publication'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_publication')

    # ### end Alembic commands ###
