"""Ajout de nb_donateurs, is_reussi, moyenne_sentiment dans Don

Revision ID: a3e5aa437bd2
Revises: b3a83cdc243d
Create Date: 2025-06-02 15:38:46.348681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e5aa437bd2'
down_revision = 'b3a83cdc243d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.drop_column('moyenne_sentiment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moyenne_sentiment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
