"""Update length of description

Revision ID: a563c669c3ca
Revises: f96b19482432
Create Date: 2025-04-08 11:57:38.061728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a563c669c3ca'
down_revision = 'f96b19482432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.alter_column('description_association',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('adresse',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.alter_column('adresse',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('description_association',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
