"""ajout statut publication

Revision ID: acc0fe03b5e1
Revises: 265e4c2ef8ae
Create Date: 2025-05-06 15:46:26.486612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc0fe03b5e1'
down_revision = '265e4c2ef8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
