"""Ajout de nb_donateurs, is_reussi, moyenne_sentiment dans Don

Revision ID: b3a83cdc243d
Revises: d4bfc19f6b3f
Create Date: 2025-06-02 15:19:57.051759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a83cdc243d'
down_revision = 'd4bfc19f6b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nb_donateurs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_reussi', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('moyenne_sentiment', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.drop_column('moyenne_sentiment')
        batch_op.drop_column('is_reussi')
        batch_op.drop_column('nb_donateurs')

    # ### end Alembic commands ###
