"""Ajout du champ id_don à Notification

Revision ID: d4bfc19f6b3f
Revises: 7de76f819ccc
Create Date: 2025-05-29 18:42:21.810424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bfc19f6b3f'
down_revision = '7de76f819ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_don', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'dons', ['id_don'], ['id_don'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_don')

    # ### end Alembic commands ###
