"""add parent_comment_id to commentaires

Revision ID: f0af1e8efc6a
Revises: 8d665efc9d51
Create Date: 2025-09-24 17:41:08.985317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0af1e8efc6a'
down_revision = '8d665efc9d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_comment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_commentaires_parent_comment_id'), ['parent_comment_id'], unique=False)
        batch_op.create_foreign_key(None, 'commentaires', ['parent_comment_id'], ['id_commentaire'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commentaires', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_commentaires_parent_comment_id'))
        batch_op.drop_column('parent_comment_id')

    # ### end Alembic commands ###
