"""Ajout champ objectif dans Don

Revision ID: f96b19482432
Revises: 88754bb3878a
Create Date: 2025-04-07 17:28:55.289094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96b19482432'
down_revision = '88754bb3878a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectif', sa.Float(), nullable=False))
        batch_op.alter_column('montant_collecte',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dons', schema=None) as batch_op:
        batch_op.alter_column('montant_collecte',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('objectif')

    # ### end Alembic commands ###
