"""Increase nom_complet length

Revision ID: fb031f120d88
Revises: 524cbca21221
Create Date: 2025-06-23 15:28:08.321217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb031f120d88'
down_revision = '524cbca21221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.alter_column('nom_complet',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('associations', schema=None) as batch_op:
        batch_op.alter_column('nom_complet',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
